<? $this->pagetitle = 'Создание записки | '. $this->process->user->username?>
<? if($note = $this->note): ?>
	Записка успешно создана <a href="<?= $this->process->getRouter()->generateLinkBy('user-note', $note)?>"><?=$note->id?></a>
<? else: ?>
	<form method="post" action="">
		<label><input type="hidden" name="id" value="<?=$this->process->user->id?>"/></label>
		<p><label>Название:<br/><input type="text" name="title" value=""/></label></p>
		<p><label>Текст:<br/><textarea name="text"></textarea></label></p>
		<p><input type="submit" value="Создать записку"> | <a href="<?=$this->process->linkBy('user',$this->process->user)?>">Отмена</a></p>
	</form>
<? endif ?>