<?
/** @var \Jungle\Application\Dispatcher\ProcessInterface $p */
$p = $this->process;
$note = $p->note;
$this->pagetitle = 'Редактирование записки - ' . $note->title . ' | ' . $note->user->username;
?><? if($p->title && $this->note): ?>
	<? $this->note = $note;include '../user/note.phtml'?>
	<p style="font-weight:bold;">Записка успешно изменена</p>
<? else: ?>
	<form method="post" action="<?=$p->linkBy('user-note-update', $note)?>">
		<label><input type="hidden" name="id" value="<?=$note->id?>"/></label>
		<p><label>Название:<br/><input type="text" name="title" value="<?=$note->title?>"/></label></p>
		<p><label>Текст:<br/><textarea name="text"><?=$note->text?></textarea></label></p>
		<p><input type="submit" value="Сохранить записку"> | <a href="<?=$p->linkBy('user-note',$note)?>">Отмена</a></p>
	</form>
<? endif ?>