<? $this->pagetitle = 'Создание пользователя'?>
<? if($user = $this->user): ?>
	Пользователь <a href="<?= $this->process->linkBy('user', $user)?>"><?=$user->username?></a> успешно создан.
<? else: ?>
	<form method="post" action="<?=$this->process->linkBy('user-create')?>" id="sendemail">
		<p>
			<label>Имя пользователя:<br/>
				<input type="text" name="username" value=""/>
			</label>
		</p>
		<p>
			<label>Пароль:<br/>
				<input type="password" name="password" />
			</label>
		</p>
		<p>
			<label>Подтверждение пароля:<br/>
				<input type="password" name="password_confirm" />
			</label>
		</p>
		<p>
			<input type="submit" value="Создать пользователя">
			<a href="<?=$this->process->linkMain()?>">Отмена</a>
		</p>
	</form>
<? endif ?>