<?php

$this->pagetitle = 'Информация о '. $this->user->username;

?>
<h2>Пользователь <?=$this->user->username?>!</h2>
<?if(isset($this->services->session->user_id) && $this->services->session->user_id === $this->user->id):?>
<p style=""><a href="<?=$this->process->linkBy('user-update',$this->user);?>">Редактировать</a></p>
<p style=""><a href="<?=$this->process->linkBy('user-delete',$this->user);?>">Удалить</a></p>
<?endif?>
<? include './notes.phtml'?>
