<? if($note = $this->note): ?>
	Записка успешно создана <?= $this->process->getRouter()->generateLinkBy('user-note', $note)?>
<? else: ?>
	<form method="post" action="">
		<label>
			<input type="hidden" name="id" value="<?=$this->user->id?>"/>
		</label>
		<label>
			Назовите записку:
			<input type="text" name="title" value="<?=$this->user->id?>"/>
		</label>
		<label>
			Текст записки:
			<textarea name="text"></textarea>
		</label>
		<input type="submit" value="Создать записку">
	</form>
<? endif ?>