<? $user = $this->note->user?>
<? $this->pagetitle =  $this->note->title . ' - '. $user->username ?>
<h2><?=$this->note->title?></h2>
<p>
	<?=$this->note->text?>
</p>
<?if($this->services->account->getUser() === $user):?>
<p>
	<a href="<?= $this->process->linkBy('user-note-update', $this->note)?>">Редактировать</a>
</p>
<?endif?>
<p>
	Пользователь: <a href="<?= $this->process->linkBy('user-short', $user)?>"><?=$user->username?></a>
</p>

<h4>Комментарии</h4>
<a href="<?= $this->process->linkBy('user-note-comment-create', $this->note)?>">Добавить</a>
<section>
	<? foreach($this->note->comments as $comment):?>
	<div class="article">
		<h5><?=$comment->user->username?></h5>
		<p><?=$comment->text?></p>
	</div>
	<? endforeach; ?>
</section>