<?
/** @var \Jungle\Application\Dispatcher\ProcessInterface $p */
$p = $this->process;
$user = $p->user;
$this->pagetitle = 'Редактирование пользователя - ' . $user->username;
?><? if($p->username && $this->user): ?>
	<p style="font-weight:bold;">Пользователь <a href="<?=$p->linkBy('user',$user)?>"><?=$user->username?></a> успешно изменен</p>
<? else: ?>
	<form method="post" action="<?=$p->linkBy('user-update', $user)?>">
		<p>
			<label>Имя пользователя:<br/>
				<input type="text" name="username" value="<?=$user->username?>"/>
			</label>
		</p>
		<p>
			<input type="submit" value="Сохранить">
			<a href="<?=$p->linkBy('user',$user)?>">Отмена</a>
		</p>
	</form>
<? endif ?>
